name: Deploy INFRA on AWS
#on: workflow_dispatch
on:
  push:
    branches:
      - 'infra-terraform'

jobs:
  terraform-plan:
    name: 'Terraform-Plan'
    uses: ./.github/workflows/terraform_reusable_plan.yml
    strategy:
      matrix:
        paths: [tf-aws-resources/develop/ecr, tf-aws-resources/develop/s3]
    with:
      terraform_path: ${{ matrix.paths }}
      environment: "Develop"
      aws_resource: "ECR"

  manual-approval:
    name: Manual Approval to CREATE
    runs-on: ubuntu-latest
    environment: Manual Approval CREATE
    needs: terraform-plan         
    permissions:
      issues: write      
    steps:
    - name: Await Manual Approval
      run: echo "Waiting manual approve to CREATE the terraform resources..."

  terraform-apply:
    name: 'Terraform-Apply'
    needs: manual-approval
    uses: ./.github/workflows/terraform_reusable_apply.yml
    strategy:
      matrix:
        paths: [tf-aws-resources/develop/ecr, tf-aws-resources/develop/s3]
    with:
      terraform_path: ${{ matrix.paths }}
      environment: "Develop"
      aws_resource: "ECR"

  manual-approval-validate-destroy:
    name: Manual Approval to show resources to DESTROY
    uses: ./.github/workflows/terraform_reusable_validate_destroy.yml
    needs: terraform-apply 
    strategy:
      matrix:
        paths: [tf-aws-resources/develop/ecr, tf-aws-resources/develop/s3]
    with:
      terraform_path: ${{ matrix.paths }}
      environment: "Develop"
      aws_resource: "ECR"
      
  manual-approval-destroy:
    name: Manual Approval to REALLY DESTROY
    uses: ./.github/workflows/terraform_reusable_destroy.yml
    needs: manual-approval-validate-destroy 
    strategy:
      matrix:
        paths: [tf-aws-resources/develop/ecr, tf-aws-resources/develop/s3]
    with:
      terraform_path: ${{ matrix.paths }}
      environment: "Develop"
      aws_resource: "ECR"