name: Deploy INFRA on AWS
#on: workflow_dispatch
on:
  push:
    branches:
      - 'infra-terraform'

jobs:
  terraform-plan:
    name: 'Terraform-Plan'
    uses: ./.github/workflows/terraform_reusable_plan.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"

  manual-approval:
    name: Manual Approval to CREATE
    runs-on: ubuntu-latest
    environment: Manual Approval CREATE
    needs: terraform-plan
          
    permissions:
      issues: write
      
    steps:
    - name: Await Manual Approval
      run: echo "Waiting manual approve to CREATE the terraform resources..."

  terraform-apply:
    name: 'Terraform-Apply'
    needs: manual-approval
    uses: ./.github/workflows/terraform_reusable_action.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"
      terraform_action: "apply"

  manual-approval-destroy:
    name: Manual Approval to DESTROY
    runs-on: ubuntu-latest
    environment: Manual Approval DESTROY
    needs: terraform-apply
          
    permissions:
      issues: write
      
    steps:
    - name: Await Manual Approval to Destroy
      run: echo "Waiting manual approve to DESTROY the terraform resources..."

  terraform-destroy:
    name: 'Terraform-Destroy'
    needs: manual-approval-destroy
    uses: ./.github/workflows/terraform_reusable_action.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"
      terraform_action: "destroy"