name: Deploy INFRA on AWS
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - 'infra-terraform'
#       - 'staging'
#       - 'main'

jobs:
  setup-terraform-paths:
    name: Setting the Terraform Paths
    runs-on: ubuntu-latest
    outputs:
      paths: ${{ steps.set-paths.outputs.paths }}
    steps:
      - name: Set the paths from AWS services
        id: set-paths

        # PARA CRIAR NOVOS RECURSOS VIA TERRAFORM, NECESSARIO ALTERAR APENAS ESSA CONFIGURACAO.
        # INSERIR O NOME DAS PASTA COM OS ARQUIVOS DO TERRAFORM DE CADA RECURSO AWS [\"ecr\", \"s3\"]
        # SE ATENTAR A ESTRUTURA DA SINTAXE, A QUAL DEVE SER MANTIDA
        # CASO ALGUM DOS RECURSOS TF LOCALIZADOS NO DIRETORIO NAO NECESSITAR SER CRIADO, BASTA REMOVE-LO DA CONFIGURACAO ABAIXO
        run: echo "::set-output name=paths::[\"ecr\", \"s3\"]" 

  terraform-plan:
    needs: setup-terraform-paths
    uses: ./.github/workflows/terraform_reusable_plan.yml
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-terraform-paths.outputs.paths) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}

  manual-approval:
    name: Manual Approval to CREATE
    runs-on: ubuntu-latest
    environment: Manual Approval CREATE
    needs: terraform-plan         
    permissions:
      issues: write      
    steps:
    - name: Await Manual Approval
      run: echo "Waiting manual approve to CREATE the terraform resources..."

  terraform-apply:
    needs: [manual-approval, setup-terraform-paths]
    uses: ./.github/workflows/terraform_reusable_apply.yml
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-terraform-paths.outputs.paths) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}

  manual-approval-validate-destroy:
    uses: ./.github/workflows/terraform_reusable_validate_destroy.yml
    needs: [terraform-apply, setup-terraform-paths]
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-terraform-paths.outputs.paths) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}
      
  manual-approval-destroy:
    name: Manual Approval to REALLY DESTROY
    uses: ./.github/workflows/terraform_reusable_destroy.yml
    needs: [manual-approval-validate-destroy, setup-terraform-paths]
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-terraform-paths.outputs.paths) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}