name: Deploy to AWS

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::236730285067:role/role_GitHubActionsIntegration

    - name: Create S3
      run: |
        #aws s3api create-bucket --bucket test-bucket-tty5544 --region us-east-1
        #aws s3 rb s3://test-bucket-tty5543 --region us-east-1 --force
        #aws s3 rb s3://test-bucket-tty5544 --region us-east-1 --force
        aws s3 rb s3://cf-templates-ykc40sjj1wup-us-east-1 --region us-east-1 --force
