name: Deploy INFRA on AWS
on: workflow_dispatch
# on:
#   push:
#     branches:
#       - 'infra-terraform'

jobs:
  terraform-plan:
    name: 'Terraform-Plan'
    uses: ./.github/workflows/terraform_reusable_plan.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"

  manual-approval:
    name: Manual Approval to CREATE
    runs-on: ubuntu-latest
    environment: Manual Approval CREATE
    needs: terraform-plan
          
    permissions:
      issues: write
      
    steps:
    - name: Await Manual Approval
      run: echo "Waiting manual approve to CREATE the terraform resources..."

  terraform-apply:
    name: 'Terraform-Apply'
    needs: manual-approval
    uses: ./.github/workflows/terraform_reusable_action.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"
      terraform_action: "apply"

  manual-approval-destroy:
    name: Manual Approval to DESTROY
    runs-on: ubuntu-latest
    environment: Manual Approval DESTROY
    needs: terraform-apply
          
    permissions:
      issues: write
      
    steps:
    - name: Configure AWS Credentials using OIDC
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-region: us-east-1
        role-to-assume: arn:aws:iam::236730285067:role/role_GitHubActionsIntegration  

    # Install the latest version of Terraform CLI
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: "1.1.7"

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      run: |
        cd tf-aws-resources/develop/ecr
        terraform init

    # Generates an execution to show the resources to destroy for Terraform
    - name: Terraform Plan Destoy
      run: |
        cd tf-aws-resources/develop/ecr
        terraform destroy

    - name: Await Manual Approval to Destroy
      run: echo "Waiting manual approve to DESTROY the terraform resources..."
      
  terraform-destroy:
    name: 'Terraform-Destroy'
    needs: manual-approval-destroy
    uses: ./.github/workflows/terraform_reusable_action.yml
    with:
      terraform_path: "tf-aws-resources/develop/ecr"
      environment: "Develop"
      aws_resource: "ECR"
      terraform_action: "destroy"