name: Deploy INFRA on AWS
#on: workflow_dispatch
on:
  push:
    branches:
      - 'infra-terraform'

jobs:
  setup-matrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Definir matriz de paths
        id: set-matrix
        run: echo "::set-output name=matrix::[\"ecr\", \"s3\"]"

  terraform-plan:
    needs: setup-matrix
    uses: ./.github/workflows/terraform_reusable_plan.yml
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}

  manual-approval:
    name: Manual Approval to CREATE
    runs-on: ubuntu-latest
    environment: Manual Approval CREATE
    needs: terraform-plan         
    permissions:
      issues: write      
    steps:
    - name: Await Manual Approval
      run: echo "Waiting manual approve to CREATE the terraform resources..."

  terraform-apply:
    needs: [manual-approval, setup-matrix]
    uses: ./.github/workflows/terraform_reusable_apply.yml
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}

  manual-approval-validate-destroy:
    uses: ./.github/workflows/terraform_reusable_validate_destroy.yml
    needs: [terraform-apply, setup-matrix]
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}
      
  manual-approval-destroy:
    name: Manual Approval to REALLY DESTROY
    uses: ./.github/workflows/terraform_reusable_destroy.yml
    needs: [manual-approval-validate-destroy, setup-matrix]
    strategy:
      matrix:
        paths: ${{ fromJson(needs.setup-matrix.outputs.matrix) }}
    with:
      environment: "Develop"
      resource_path: ${{ matrix.paths }}